### ISSUE TITLE
 Test Channel

### ISSUE THREAD

**Issue by ramosglauco** [WildRikku/OctoPrint-SpoolManager#21]
Hello. Could you make a test version available with the database improvements (even if they are not completely ready yet)? I still can't use the plugin because it's not possible to share the database with other instances. Thank you!

**Comment by WildRikku** [comment]
Hi, I am already working on that. The code is ready as a beta, I just want to make the release smooth and re-usable for future tests and ensure future updates work even for the beta / testing channel. It won't be long and I'd like to hear feedback once it's out!

I am closing this ticket as there are already others. When you get the update, feel free to open a new one if you have issues or feedback.
